PROJECT_NAME := hello-world
CPPFLAGS += -Wno-error=switch -Wno-error=maybe-uninitialized
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/components
EXTRA_COMPONENT_DIRS += ../../
COMPONENT_SRCDIRS := .
MAKEFLAGS +=
include $(IDF_PATH)/make/project.mk
