on: [push]

jobs:
  esp32-test:
    runs-on: ubuntu-latest
    name: Test with ESP-IDF
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: test
        container:
        image: espressif/idf:release-v3.3
        volumes:
          - .:/project
        options: --cpus 1
        run: make -C /project/test/esp32/run.sh
