on: [push]

jobs:
  esp32-test:
    runs-on: ubuntu-latest
    name: Test with ESP-IDF
    container:
      image: espressif/idf:release-v3.3
      options: --cpus 1
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: ls -lah
        run: ls -lah test/esp32
      - name: test
        run: make -C test/esp32/run.sh
