on: [push]

jobs:
  esp32-test:
    runs-on: ubuntu-latest
    name: Test with ESP-IDF
    container: espressif/idf:release-v3.3
    steps:
      - name: check out
        uses: actions/checkout@v2
        path: /project
      - name: test
        run: make -C /project/test/esp32/run.sh
