on: [push]

jobs:
  test-direct:
    runs-on: ubuntu-latest
    name: Test in docker container
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: check out arduino
        uses: actions/checkout@v2
        with:
          repo: https://github.com/espressif/arduino-esp32.git
          path: test/esp32/arduino-esp32
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            test/esp32/build
          key: ${{ runner.os }}-esp32-build
      - name: run test in docker
        run: docker run --rm -v $PWD:/project -w /project espressif/idf:release-v3.3 make -C test/esp32 -j5 --quiet all
