on: [push]

jobs:
  esp32-test:
    runs-on: ubuntu-latest
    name: Test with ESP-IDF
    container:
      image: espressif/idf:release-v3.3
      volumes:
        - .:/project
      options: --cpus 1
    steps:
      - name: check out
        uses: actions/checkout@v2
        path: /project
      - name: test
        run: make -C /project/test/esp32/run.sh
